/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *             File:  Rte_Hook.h
 *           Config:  last364.dpa
 *      ECU-Project:  last364
 *
 *        Generator:  MICROSAR RTE Generator Version 4.29.0
 *                    RTE Core Version 1.29.0
 *          License:  CBD2200508
 *
 *      Description:  Header file containing definitions for VFB tracing
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * Names of available VFB-Trace-Hooks
 **********************************************************************************************************************
 *
 * Not configured:
 *
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_WriteOnlyDID_DID_DataObject_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_WriteOnlyDID_DID_DataObject_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_FreezeCurrentState_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_FreezeCurrentState_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ResetToDefault_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ResetToDefault_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReturnControlToECU_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReturnControlToECU_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ShortTermAdjustment_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ShortTermAdjustment_Start
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_WriteData_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_RequestResults_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_RequestResults_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_RequestResults_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_RequestResults_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_Start_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_Start_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Start_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Start_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Stop_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Stop_Start
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_CompareKey_Return
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_CompareKey_Start
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_GetSeed_Return
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_GetSeed_Start
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_CompareKey_Return
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_CompareKey_Start
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_GetSeed_Return
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_GetSeed_Start
 *  Rte_CallHook_DemMaster_0_CBInitEvt_DTC_0x000002_InitMonitorForEvent_Return
 *  Rte_CallHook_DemMaster_0_CBInitEvt_DTC_0x000002_InitMonitorForEvent_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_DID_0x1_DID_Data_GlobalTime_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_DID_0x1_DID_Data_GlobalTime_ReadData_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x12_DID_Data_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x12_DID_Data_ReadData_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x13_DID_Data_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x13_DID_Data_ReadData_Start
 *  Rte_CallHook_DemSatellite_0_CBReadData_DID_0x1_DID_Data_GlobalTime_ReadData_Return
 *  Rte_CallHook_DemSatellite_0_CBReadData_DID_0x1_DID_Data_GlobalTime_ReadData_Start
 *  Rte_CallHook_DemSatellite_0_CBReadData_PID_0x12_DID_Data_ReadData_Return
 *  Rte_CallHook_DemSatellite_0_CBReadData_PID_0x12_DID_Data_ReadData_Start
 *  Rte_CallHook_DemSatellite_0_CBReadData_PID_0x13_DID_Data_ReadData_Return
 *  Rte_CallHook_DemSatellite_0_CBReadData_PID_0x13_DID_Data_ReadData_Start
 *  Rte_CallHook_StartApp_ComM_UserRequest_RequestComMode_Return
 *  Rte_CallHook_StartApp_ComM_UserRequest_RequestComMode_Start
 *  Rte_CallHook_StartApp_EcuM_StateRequest_RequestRUN_Return
 *  Rte_CallHook_StartApp_EcuM_StateRequest_RequestRUN_Start
 *  Rte_ReadHook_MotorCdd_Pp_MotorCtrlCmd_MotorMode_Return
 *  Rte_ReadHook_MotorCdd_Pp_MotorCtrlCmd_MotorMode_Start
 *  Rte_ReadHook_MotorCdd_Pp_MotorCurrentRef_Id_Ref_Return
 *  Rte_ReadHook_MotorCdd_Pp_MotorCurrentRef_Id_Ref_Start
 *  Rte_ReadHook_MotorCdd_Pp_MotorCurrentRef_Iq_Ref_Return
 *  Rte_ReadHook_MotorCdd_Pp_MotorCurrentRef_Iq_Ref_Start
 *  Rte_ReadHook_MotorControll_Pp_MotorDcBusVoltage_Vbus_Return
 *  Rte_ReadHook_MotorControll_Pp_MotorDcBusVoltage_Vbus_Start
 *  Rte_ReadHook_MotorControll_Pp_MotorElectricalAngle_ElectricAngle_Return
 *  Rte_ReadHook_MotorControll_Pp_MotorElectricalAngle_ElectricAngle_Start
 *  Rte_ReadHook_MotorControll_Pp_MotorFaultStatus_tle9180_Ov_Fault_Return
 *  Rte_ReadHook_MotorControll_Pp_MotorFaultStatus_tle9180_Ov_Fault_Start
 *  Rte_Runnable_BswM_BswM_MainFunction_Return
 *  Rte_Runnable_BswM_BswM_MainFunction_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Start
 *  Rte_Runnable_ComM_GetCurrentComMode_Return
 *  Rte_Runnable_ComM_GetCurrentComMode_Start
 *  Rte_Runnable_ComM_GetInhibitionStatus_Return
 *  Rte_Runnable_ComM_GetInhibitionStatus_Start
 *  Rte_Runnable_ComM_GetMaxComMode_Return
 *  Rte_Runnable_ComM_GetMaxComMode_Start
 *  Rte_Runnable_ComM_GetRequestedComMode_Return
 *  Rte_Runnable_ComM_GetRequestedComMode_Start
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Return
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Start
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Return
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Start
 *  Rte_Runnable_ComM_PreventWakeUp_Return
 *  Rte_Runnable_ComM_PreventWakeUp_Start
 *  Rte_Runnable_ComM_ReadInhibitCounter_Return
 *  Rte_Runnable_ComM_ReadInhibitCounter_Start
 *  Rte_Runnable_ComM_RequestComMode_Return
 *  Rte_Runnable_ComM_RequestComMode_Start
 *  Rte_Runnable_ComM_ResetInhibitCounter_Return
 *  Rte_Runnable_ComM_ResetInhibitCounter_Start
 *  Rte_Runnable_ComM_SetECUGroupClassification_Return
 *  Rte_Runnable_ComM_SetECUGroupClassification_Start
 *  Rte_Runnable_Dcm_Dcm_MainFunction_Return
 *  Rte_Runnable_Dcm_Dcm_MainFunction_Start
 *  Rte_Runnable_Dcm_GetActiveProtocol_Return
 *  Rte_Runnable_Dcm_GetActiveProtocol_Start
 *  Rte_Runnable_Dcm_GetRequestKind_Return
 *  Rte_Runnable_Dcm_GetRequestKind_Start
 *  Rte_Runnable_Dcm_GetSecurityLevel_Return
 *  Rte_Runnable_Dcm_GetSecurityLevel_Start
 *  Rte_Runnable_Dcm_GetSesCtrlType_Return
 *  Rte_Runnable_Dcm_GetSesCtrlType_Start
 *  Rte_Runnable_Dcm_ResetToDefaultSession_Return
 *  Rte_Runnable_Dcm_ResetToDefaultSession_Start
 *  Rte_Runnable_Dcm_SetActiveDiagnostic_Return
 *  Rte_Runnable_Dcm_SetActiveDiagnostic_Start
 *  Rte_Runnable_DemMaster_0_ClearDTC_Return
 *  Rte_Runnable_DemMaster_0_ClearDTC_Start
 *  Rte_Runnable_DemMaster_0_Dem_MasterMainFunction_Return
 *  Rte_Runnable_DemMaster_0_Dem_MasterMainFunction_Start
 *  Rte_Runnable_DemMaster_0_GetDTCOfEvent_Return
 *  Rte_Runnable_DemMaster_0_GetDTCOfEvent_Start
 *  Rte_Runnable_DemMaster_0_GetDTCStatusAvailabilityMask_Return
 *  Rte_Runnable_DemMaster_0_GetDTCStatusAvailabilityMask_Start
 *  Rte_Runnable_DemMaster_0_GetDebouncingOfEvent_Return
 *  Rte_Runnable_DemMaster_0_GetDebouncingOfEvent_Start
 *  Rte_Runnable_DemMaster_0_GetEventEnableCondition_Return
 *  Rte_Runnable_DemMaster_0_GetEventEnableCondition_Start
 *  Rte_Runnable_DemMaster_0_GetEventExtendedDataRecordEx_Return
 *  Rte_Runnable_DemMaster_0_GetEventExtendedDataRecordEx_Start
 *  Rte_Runnable_DemMaster_0_GetEventFailed_Return
 *  Rte_Runnable_DemMaster_0_GetEventFailed_Start
 *  Rte_Runnable_DemMaster_0_GetEventFreezeFrameDataEx_Return
 *  Rte_Runnable_DemMaster_0_GetEventFreezeFrameDataEx_Start
 *  Rte_Runnable_DemMaster_0_GetEventMemoryOverflow_Return
 *  Rte_Runnable_DemMaster_0_GetEventMemoryOverflow_Start
 *  Rte_Runnable_DemMaster_0_GetEventStatus_Return
 *  Rte_Runnable_DemMaster_0_GetEventStatus_Start
 *  Rte_Runnable_DemMaster_0_GetEventTested_Return
 *  Rte_Runnable_DemMaster_0_GetEventTested_Start
 *  Rte_Runnable_DemMaster_0_GetEventUdsStatus_Return
 *  Rte_Runnable_DemMaster_0_GetEventUdsStatus_Start
 *  Rte_Runnable_DemMaster_0_GetFaultDetectionCounter_Return
 *  Rte_Runnable_DemMaster_0_GetFaultDetectionCounter_Start
 *  Rte_Runnable_DemMaster_0_GetIndicatorStatus_Return
 *  Rte_Runnable_DemMaster_0_GetIndicatorStatus_Start
 *  Rte_Runnable_DemMaster_0_GetMonitorStatus_Return
 *  Rte_Runnable_DemMaster_0_GetMonitorStatus_Start
 *  Rte_Runnable_DemMaster_0_GetNumberOfEventMemoryEntries_Return
 *  Rte_Runnable_DemMaster_0_GetNumberOfEventMemoryEntries_Start
 *  Rte_Runnable_DemMaster_0_GetOperationCycleState_Return
 *  Rte_Runnable_DemMaster_0_GetOperationCycleState_Start
 *  Rte_Runnable_DemMaster_0_PostRunRequested_Return
 *  Rte_Runnable_DemMaster_0_PostRunRequested_Start
 *  Rte_Runnable_DemMaster_0_SelectDTC_Return
 *  Rte_Runnable_DemMaster_0_SelectDTC_Start
 *  Rte_Runnable_DemMaster_0_SetOperationCycleState_Return
 *  Rte_Runnable_DemMaster_0_SetOperationCycleState_Start
 *  Rte_Runnable_DemSatellite_0_Dem_SatelliteMainFunction_Return
 *  Rte_Runnable_DemSatellite_0_Dem_SatelliteMainFunction_Start
 *  Rte_Runnable_DemSatellite_0_GetDTCOfEvent_Return
 *  Rte_Runnable_DemSatellite_0_GetDTCOfEvent_Start
 *  Rte_Runnable_DemSatellite_0_GetDebouncingOfEvent_Return
 *  Rte_Runnable_DemSatellite_0_GetDebouncingOfEvent_Start
 *  Rte_Runnable_DemSatellite_0_GetEventEnableCondition_Return
 *  Rte_Runnable_DemSatellite_0_GetEventEnableCondition_Start
 *  Rte_Runnable_DemSatellite_0_GetEventExtendedDataRecordEx_Return
 *  Rte_Runnable_DemSatellite_0_GetEventExtendedDataRecordEx_Start
 *  Rte_Runnable_DemSatellite_0_GetEventFailed_Return
 *  Rte_Runnable_DemSatellite_0_GetEventFailed_Start
 *  Rte_Runnable_DemSatellite_0_GetEventFreezeFrameDataEx_Return
 *  Rte_Runnable_DemSatellite_0_GetEventFreezeFrameDataEx_Start
 *  Rte_Runnable_DemSatellite_0_GetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetEventStatus_Start
 *  Rte_Runnable_DemSatellite_0_GetEventTested_Return
 *  Rte_Runnable_DemSatellite_0_GetEventTested_Start
 *  Rte_Runnable_DemSatellite_0_GetEventUdsStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetEventUdsStatus_Start
 *  Rte_Runnable_DemSatellite_0_GetFaultDetectionCounter_Return
 *  Rte_Runnable_DemSatellite_0_GetFaultDetectionCounter_Start
 *  Rte_Runnable_DemSatellite_0_GetMonitorStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetMonitorStatus_Start
 *  Rte_Runnable_DemSatellite_0_ResetEventDebounceStatus_Return
 *  Rte_Runnable_DemSatellite_0_ResetEventDebounceStatus_Start
 *  Rte_Runnable_DemSatellite_0_ResetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_ResetEventStatus_Start
 *  Rte_Runnable_DemSatellite_0_SetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_SetEventStatus_Start
 *  Rte_Runnable_DigApp_CSDataServices_DID_0x1_DID_Data_GlobalTime_ReadData_Return
 *  Rte_Runnable_DigApp_CSDataServices_DID_0x1_DID_Data_GlobalTime_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_Boot_Software_Identification_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_Boot_Software_Identification_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_Boot_Software_Identification_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_Boot_Software_Identification_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_Boot_Software_Identification_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_Boot_Software_Identification_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_NumberOfModules_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_NumberOfModules_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_NumberOfModules_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_NumberOfModules_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_NumberOfModules_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_Boot_Software_NumberOfModules_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_DID_0xF410_DID_Data_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_DID_0xF410_DID_Data_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_DID_0xF410_DID_Data_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_DID_0xF410_DID_Data_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_DID_0xF412_DID_Data_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_DID_0xF412_DID_Data_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_DID_0xF412_DID_Data_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_DID_0xF412_DID_Data_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_DID_0xF413_DID_Data_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_DID_0xF413_DID_Data_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_DID_0xF413_DID_Data_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_DID_0xF413_DID_Data_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_EcuIdentification_Part_Number_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_EcuIdentification_Part_Number_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_EcuIdentification_Part_Number_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_EcuIdentification_Part_Number_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_EcuIdentification_Part_Number_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_EcuIdentification_Part_Number_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Example_ReadWriteData_GlobalTime_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Example_ReadWriteData_GlobalTime_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Example_ReadWriteData_GlobalTime_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Example_ReadWriteData_GlobalTime_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Example_ReadWriteData_GlobalTime_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_Example_ReadWriteData_GlobalTime_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_Hardware_Version_Hardware_Version_Number_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Hardware_Version_Hardware_Version_Number_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Hardware_Version_Hardware_Version_Number_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Hardware_Version_Hardware_Version_Number_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Hardware_Version_Hardware_Version_Number_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_Hardware_Version_Hardware_Version_Number_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_FreezeCurrentState_Return
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_FreezeCurrentState_Start
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ResetToDefault_Return
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ResetToDefault_Start
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ReturnControlToECU_Return
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ReturnControlToECU_Start
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ShortTermAdjustment_Return
 *  Rte_Runnable_DigApp_DataServices_SampleIoControl_DID_Data_ShortTermAdjustment_Start
 *  Rte_Runnable_DigApp_DataServices_SerialNumber_SerialNumber_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_SerialNumber_SerialNumber_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_SerialNumber_SerialNumber_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_SerialNumber_SerialNumber_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_SerialNumber_SerialNumber_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_SerialNumber_SerialNumber_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_Spare_Part_Number_Spare_Part_Number_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Spare_Part_Number_Spare_Part_Number_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Spare_Part_Number_Spare_Part_Number_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Spare_Part_Number_Spare_Part_Number_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Spare_Part_Number_Spare_Part_Number_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_Spare_Part_Number_Spare_Part_Number_WriteData_Start
 *  Rte_Runnable_DigApp_DataServices_Vehicle_Identification_VIN_ConditionCheckRead_Return
 *  Rte_Runnable_DigApp_DataServices_Vehicle_Identification_VIN_ConditionCheckRead_Start
 *  Rte_Runnable_DigApp_DataServices_Vehicle_Identification_VIN_ReadData_Return
 *  Rte_Runnable_DigApp_DataServices_Vehicle_Identification_VIN_ReadData_Start
 *  Rte_Runnable_DigApp_DataServices_Vehicle_Identification_VIN_WriteData_Return
 *  Rte_Runnable_DigApp_DataServices_Vehicle_Identification_VIN_WriteData_Start
 *  Rte_Runnable_DigApp_Dig_Init_Return
 *  Rte_Runnable_DigApp_Dig_Init_Start
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_RequestResults_Return
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_RequestResults_Start
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_StartOnly_RequestResults_Return
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_StartOnly_RequestResults_Start
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_StartOnly_Start_Return
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_StartOnly_Start_Start
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_Start_Return
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_Start_Start
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_Stop_Return
 *  Rte_Runnable_DigApp_RoutineServices_SampleRoutineControl_Stop_Start
 *  Rte_Runnable_DigApp_SecurityAccess_Level_3_CompareKey_Return
 *  Rte_Runnable_DigApp_SecurityAccess_Level_3_CompareKey_Start
 *  Rte_Runnable_DigApp_SecurityAccess_Level_3_GetSeed_Return
 *  Rte_Runnable_DigApp_SecurityAccess_Level_3_GetSeed_Start
 *  Rte_Runnable_DigApp_SecurityAccess_UnlockedL1_CompareKey_Return
 *  Rte_Runnable_DigApp_SecurityAccess_UnlockedL1_CompareKey_Start
 *  Rte_Runnable_DigApp_SecurityAccess_UnlockedL1_GetSeed_Return
 *  Rte_Runnable_DigApp_SecurityAccess_UnlockedL1_GetSeed_Start
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Return
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Start
 *  Rte_Runnable_EcuM_GetBootTarget_Return
 *  Rte_Runnable_EcuM_GetBootTarget_Start
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Start
 *  Rte_Runnable_EcuM_GetShutdownCause_Return
 *  Rte_Runnable_EcuM_GetShutdownCause_Start
 *  Rte_Runnable_EcuM_GetShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetShutdownTarget_Start
 *  Rte_Runnable_EcuM_GetStateWrapper_Return
 *  Rte_Runnable_EcuM_GetStateWrapper_Start
 *  Rte_Runnable_EcuM_ReleasePOSTRUN_Return
 *  Rte_Runnable_EcuM_ReleasePOSTRUN_Start
 *  Rte_Runnable_EcuM_ReleaseRUN_Return
 *  Rte_Runnable_EcuM_ReleaseRUN_Start
 *  Rte_Runnable_EcuM_RequestPOSTRUN_Return
 *  Rte_Runnable_EcuM_RequestPOSTRUN_Start
 *  Rte_Runnable_EcuM_RequestRUN_Return
 *  Rte_Runnable_EcuM_RequestRUN_Start
 *  Rte_Runnable_EcuM_SelectBootTarget_Return
 *  Rte_Runnable_EcuM_SelectBootTarget_Start
 *  Rte_Runnable_EcuM_SelectShutdownCause_Return
 *  Rte_Runnable_EcuM_SelectShutdownCause_Start
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Return
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Start
 *  Rte_Runnable_MotorCdd_AdcSampleReady_Return
 *  Rte_Runnable_MotorCdd_AdcSampleReady_Start
 *  Rte_Runnable_MotorCdd_MotorCdd_Init_Return
 *  Rte_Runnable_MotorCdd_MotorCdd_Init_Start
 *  Rte_Runnable_MotorCdd_MotorCdd_MainFunction_Return
 *  Rte_Runnable_MotorCdd_MotorCdd_MainFunction_Start
 *  Rte_Runnable_MotorCdd_Pp_MotorCdd_EnableInverter_EnableInverter_Return
 *  Rte_Runnable_MotorCdd_Pp_MotorCdd_EnableInverter_EnableInverter_Start
 *  Rte_Runnable_MotorControll_MotorControll_Init_Return
 *  Rte_Runnable_MotorControll_MotorControll_Init_Start
 *  Rte_Runnable_MotorControll_MotorControll_MainFunction_Return
 *  Rte_Runnable_MotorControll_MotorControll_MainFunction_Start
 *  Rte_Runnable_NvM_NvM_MainFunction_Return
 *  Rte_Runnable_NvM_NvM_MainFunction_Start
 *  Rte_Runnable_Os_OsCore0_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore0_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore0_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore0_swc_GetElapsedValue_Start
 *  Rte_Runnable_Os_OsCore1_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore1_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore1_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore1_swc_GetElapsedValue_Start
 *  Rte_Runnable_StartApp_StartApp_Cyclic1000ms_Return
 *  Rte_Runnable_StartApp_StartApp_Cyclic1000ms_Start
 *  Rte_Runnable_StartApp_StartApp_Cyclic10ms_Return
 *  Rte_Runnable_StartApp_StartApp_Cyclic10ms_Start
 *  Rte_Runnable_StartApp_StartApp_Cyclic1ms_Return
 *  Rte_Runnable_StartApp_StartApp_Cyclic1ms_Start
 *  Rte_Runnable_StartApp_StartApp_Cyclic250ms_Return
 *  Rte_Runnable_StartApp_StartApp_Cyclic250ms_Start
 *  Rte_Runnable_StartApp_StartApp_Init_Return
 *  Rte_Runnable_StartApp_StartApp_Init_Start
 *  Rte_SwitchAckHook_Dcm_DcmEcuReset_DcmEcuReset_Return
 *  Rte_SwitchAckHook_Dcm_DcmEcuReset_DcmEcuReset_Start
 *  Rte_SwitchAckHook_EcuM_currentMode_currentMode_Return
 *  Rte_SwitchAckHook_EcuM_currentMode_currentMode_Start
 *  Rte_SwitchHook_Dcm_DcmCommunicationControl_ComMConf_ComMChannel_CN_CAN00_5e566ad9_DcmCommunicationControl_ComMConf_ComMChannel_CN_CAN00_5e566ad9_Return
 *  Rte_SwitchHook_Dcm_DcmCommunicationControl_ComMConf_ComMChannel_CN_CAN00_5e566ad9_DcmCommunicationControl_ComMConf_ComMChannel_CN_CAN00_5e566ad9_Start
 *  Rte_SwitchHook_Dcm_DcmControlDtcSetting_DcmControlDtcSetting_Return
 *  Rte_SwitchHook_Dcm_DcmControlDtcSetting_DcmControlDtcSetting_Start
 *  Rte_SwitchHook_Dcm_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl_Return
 *  Rte_SwitchHook_Dcm_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl_Start
 *  Rte_SwitchHook_Dcm_DcmEcuReset_DcmEcuReset_Return
 *  Rte_SwitchHook_Dcm_DcmEcuReset_DcmEcuReset_Start
 *  Rte_SwitchHook_EcuM_currentMode_currentMode_Return
 *  Rte_SwitchHook_EcuM_currentMode_currentMode_Start
 *  Rte_Task_Activate
 *  Rte_Task_Dispatch
 *  Rte_Task_SetEvent
 *  Rte_Task_Terminate
 *  Rte_Task_WaitEvent
 *  Rte_Task_WaitEventRet
 *  Rte_TriggerHook_MotorCdd_Rp_AdcSampleReady_AdcSampleReady_Return
 *  Rte_TriggerHook_MotorCdd_Rp_AdcSampleReady_AdcSampleReady_Start
 *  Rte_WriteHook_MotorCdd_Pp_MotorDcBusVoltage_Vbus_Return
 *  Rte_WriteHook_MotorCdd_Pp_MotorDcBusVoltage_Vbus_Start
 *  Rte_WriteHook_MotorCdd_Pp_MotorElectricalAngle_ElectricAngle_Return
 *  Rte_WriteHook_MotorCdd_Pp_MotorElectricalAngle_ElectricAngle_Start
 *  Rte_WriteHook_MotorCdd_Pp_MotorFaultStatus_tle9180_Ov_Fault_Return
 *  Rte_WriteHook_MotorCdd_Pp_MotorFaultStatus_tle9180_Ov_Fault_Start
 *  Rte_WriteHook_MotorControll_Pp_MotorCtrlCmd_MotorMode_Return
 *  Rte_WriteHook_MotorControll_Pp_MotorCtrlCmd_MotorMode_Start
 *  Rte_WriteHook_MotorControll_Pp_MotorCurrentRef_Id_Ref_Return
 *  Rte_WriteHook_MotorControll_Pp_MotorCurrentRef_Id_Ref_Start
 *  Rte_WriteHook_MotorControll_Pp_MotorCurrentRef_Iq_Ref_Return
 *  Rte_WriteHook_MotorControll_Pp_MotorCurrentRef_Iq_Ref_Start
 *  SchM_EnterHook_Adc_KernelData_Return
 *  SchM_EnterHook_Adc_KernelData_Start
 *  SchM_EnterHook_Adc_SrcRegAccess_Return
 *  SchM_EnterHook_Adc_SrcRegAccess_Start
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_EnterHook_Crc_CriticalSection_Return
 *  SchM_EnterHook_Crc_CriticalSection_Start
 *  SchM_EnterHook_Dcm_DCM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Dcm_DCM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dma_ChEventStatus_Return
 *  SchM_EnterHook_Dma_ChEventStatus_Start
 *  SchM_EnterHook_Dma_ChannelConfigUpdate_Return
 *  SchM_EnterHook_Dma_ChannelConfigUpdate_Start
 *  SchM_EnterHook_Dma_ChannelFreezeResume_Return
 *  SchM_EnterHook_Dma_ChannelFreezeResume_Start
 *  SchM_EnterHook_Dma_ChannelHWTrigger_Return
 *  SchM_EnterHook_Dma_ChannelHWTrigger_Start
 *  SchM_EnterHook_Dma_ChannelInitDeinit_Return
 *  SchM_EnterHook_Dma_ChannelInitDeinit_Start
 *  SchM_EnterHook_Dma_ChannelStartStop_Return
 *  SchM_EnterHook_Dma_ChannelStartStop_Start
 *  SchM_EnterHook_Dma_ChannelSwitchBuffer_Return
 *  SchM_EnterHook_Dma_ChannelSwitchBuffer_Start
 *  SchM_EnterHook_Dma_InterruptStatus_Return
 *  SchM_EnterHook_Dma_InterruptStatus_Start
 *  SchM_EnterHook_Dma_MEErrorStatus_Return
 *  SchM_EnterHook_Dma_MEErrorStatus_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Fls_17_Dmu_Erase_Return
 *  SchM_EnterHook_Fls_17_Dmu_Erase_Start
 *  SchM_EnterHook_Fls_17_Dmu_Init_Return
 *  SchM_EnterHook_Fls_17_Dmu_Init_Start
 *  SchM_EnterHook_Fls_17_Dmu_Main_Return
 *  SchM_EnterHook_Fls_17_Dmu_Main_Start
 *  SchM_EnterHook_Fls_17_Dmu_ResumeErase_Return
 *  SchM_EnterHook_Fls_17_Dmu_ResumeErase_Start
 *  SchM_EnterHook_Fls_17_Dmu_UserContentCount_Return
 *  SchM_EnterHook_Fls_17_Dmu_UserContentCount_Start
 *  SchM_EnterHook_Fls_17_Dmu_Write_Return
 *  SchM_EnterHook_Fls_17_Dmu_Write_Start
 *  SchM_EnterHook_McalLib_CpuEndInit_Return
 *  SchM_EnterHook_McalLib_CpuEndInit_Start
 *  SchM_EnterHook_McalLib_PeripheralEndInit_Return
 *  SchM_EnterHook_McalLib_PeripheralEndInit_Start
 *  SchM_EnterHook_McalLib_SafetyEndInit_Return
 *  SchM_EnterHook_McalLib_SafetyEndInit_Start
 *  SchM_EnterHook_McalLib_StmTimerResolution_Return
 *  SchM_EnterHook_McalLib_StmTimerResolution_Start
 *  SchM_EnterHook_Mcu_AtomAgcReg_Return
 *  SchM_EnterHook_Mcu_AtomAgcReg_Start
 *  SchM_EnterHook_Mcu_TomTgcReg_Return
 *  SchM_EnterHook_Mcu_TomTgcReg_Start
 *  SchM_EnterHook_NvM_NVM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_NvM_NVM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Pwm_17_GtmCcu6_HandleNotification_Return
 *  SchM_EnterHook_Pwm_17_GtmCcu6_HandleNotification_Start
 *  SchM_EnterHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Return
 *  SchM_EnterHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Start
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Spi_Buffer_Update_Return
 *  SchM_EnterHook_Spi_Buffer_Update_Start
 *  SchM_EnterHook_Spi_Cancel_Seq_Return
 *  SchM_EnterHook_Spi_Cancel_Seq_Start
 *  SchM_EnterHook_Spi_ChannelLock_Return
 *  SchM_EnterHook_Spi_ChannelLock_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI0_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI0_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI1_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI1_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI2_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI2_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI3_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI3_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI4_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI4_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI5_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI5_Start
 *  SchM_EnterHook_Spi_Queue_Update_Return
 *  SchM_EnterHook_Spi_Queue_Update_Start
 *  SchM_EnterHook_Spi_SyncLock_Return
 *  SchM_EnterHook_Spi_SyncLock_Start
 *  SchM_EnterHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Adc_KernelData_Return
 *  SchM_ExitHook_Adc_KernelData_Start
 *  SchM_ExitHook_Adc_SrcRegAccess_Return
 *  SchM_ExitHook_Adc_SrcRegAccess_Start
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_ExitHook_Crc_CriticalSection_Return
 *  SchM_ExitHook_Crc_CriticalSection_Start
 *  SchM_ExitHook_Dcm_DCM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Dcm_DCM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dma_ChEventStatus_Return
 *  SchM_ExitHook_Dma_ChEventStatus_Start
 *  SchM_ExitHook_Dma_ChannelConfigUpdate_Return
 *  SchM_ExitHook_Dma_ChannelConfigUpdate_Start
 *  SchM_ExitHook_Dma_ChannelFreezeResume_Return
 *  SchM_ExitHook_Dma_ChannelFreezeResume_Start
 *  SchM_ExitHook_Dma_ChannelHWTrigger_Return
 *  SchM_ExitHook_Dma_ChannelHWTrigger_Start
 *  SchM_ExitHook_Dma_ChannelInitDeinit_Return
 *  SchM_ExitHook_Dma_ChannelInitDeinit_Start
 *  SchM_ExitHook_Dma_ChannelStartStop_Return
 *  SchM_ExitHook_Dma_ChannelStartStop_Start
 *  SchM_ExitHook_Dma_ChannelSwitchBuffer_Return
 *  SchM_ExitHook_Dma_ChannelSwitchBuffer_Start
 *  SchM_ExitHook_Dma_InterruptStatus_Return
 *  SchM_ExitHook_Dma_InterruptStatus_Start
 *  SchM_ExitHook_Dma_MEErrorStatus_Return
 *  SchM_ExitHook_Dma_MEErrorStatus_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Fls_17_Dmu_Erase_Return
 *  SchM_ExitHook_Fls_17_Dmu_Erase_Start
 *  SchM_ExitHook_Fls_17_Dmu_Init_Return
 *  SchM_ExitHook_Fls_17_Dmu_Init_Start
 *  SchM_ExitHook_Fls_17_Dmu_Main_Return
 *  SchM_ExitHook_Fls_17_Dmu_Main_Start
 *  SchM_ExitHook_Fls_17_Dmu_ResumeErase_Return
 *  SchM_ExitHook_Fls_17_Dmu_ResumeErase_Start
 *  SchM_ExitHook_Fls_17_Dmu_UserContentCount_Return
 *  SchM_ExitHook_Fls_17_Dmu_UserContentCount_Start
 *  SchM_ExitHook_Fls_17_Dmu_Write_Return
 *  SchM_ExitHook_Fls_17_Dmu_Write_Start
 *  SchM_ExitHook_McalLib_CpuEndInit_Return
 *  SchM_ExitHook_McalLib_CpuEndInit_Start
 *  SchM_ExitHook_McalLib_PeripheralEndInit_Return
 *  SchM_ExitHook_McalLib_PeripheralEndInit_Start
 *  SchM_ExitHook_McalLib_SafetyEndInit_Return
 *  SchM_ExitHook_McalLib_SafetyEndInit_Start
 *  SchM_ExitHook_McalLib_StmTimerResolution_Return
 *  SchM_ExitHook_McalLib_StmTimerResolution_Start
 *  SchM_ExitHook_Mcu_AtomAgcReg_Return
 *  SchM_ExitHook_Mcu_AtomAgcReg_Start
 *  SchM_ExitHook_Mcu_TomTgcReg_Return
 *  SchM_ExitHook_Mcu_TomTgcReg_Start
 *  SchM_ExitHook_NvM_NVM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_NvM_NVM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Pwm_17_GtmCcu6_HandleNotification_Return
 *  SchM_ExitHook_Pwm_17_GtmCcu6_HandleNotification_Start
 *  SchM_ExitHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Return
 *  SchM_ExitHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Start
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Sbc_30_Tlf35584_SBC_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Spi_Buffer_Update_Return
 *  SchM_ExitHook_Spi_Buffer_Update_Start
 *  SchM_ExitHook_Spi_Cancel_Seq_Return
 *  SchM_ExitHook_Spi_Cancel_Seq_Start
 *  SchM_ExitHook_Spi_ChannelLock_Return
 *  SchM_ExitHook_Spi_ChannelLock_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI0_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI0_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI1_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI1_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI2_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI2_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI3_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI3_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI4_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI4_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI5_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI5_Start
 *  SchM_ExitHook_Spi_Queue_Update_Return
 *  SchM_ExitHook_Spi_Queue_Update_Start
 *  SchM_ExitHook_Spi_SyncLock_Return
 *  SchM_ExitHook_Spi_SyncLock_Start
 *  SchM_ExitHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_2_Start
 *  SchM_Schedulable_BswM_BswM_MainFunction_Return
 *  SchM_Schedulable_BswM_BswM_MainFunction_Start
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Return
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Start
 *  SchM_Schedulable_CanTp_CanTp_MainFunction_Return
 *  SchM_Schedulable_CanTp_CanTp_MainFunction_Start
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Return
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Read_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Read_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Write_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Write_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Start
 *  SchM_Schedulable_Com_Com_MainFunctionRx_ComMainFunctionRx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionRx_ComMainFunctionRx_Start
 *  SchM_Schedulable_Com_Com_MainFunctionTx_ComMainFunctionTx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionTx_ComMainFunctionTx_Start
 *  SchM_Schedulable_Dcm_Dcm_MainFunction_Return
 *  SchM_Schedulable_Dcm_Dcm_MainFunction_Start
 *  SchM_Schedulable_Dem_Dem_MasterMainFunction_Return
 *  SchM_Schedulable_Dem_Dem_MasterMainFunction_Start
 *  SchM_Schedulable_Dem_Dem_SatelliteMainFunction_Return
 *  SchM_Schedulable_Dem_Dem_SatelliteMainFunction_Start
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Return
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Start
 *  SchM_Schedulable_Fee_Fee_MainFunction_Return
 *  SchM_Schedulable_Fee_Fee_MainFunction_Start
 *  SchM_Schedulable_Fls_17_Dmu_Fls_17_Dmu_MainFunction_Return
 *  SchM_Schedulable_Fls_17_Dmu_Fls_17_Dmu_MainFunction_Start
 *  SchM_Schedulable_NvM_NvM_MainFunction_Return
 *  SchM_Schedulable_NvM_NvM_MainFunction_Start
 *  SchM_Schedulable_Rte_Rte_ComSendSignalProxyPeriodic_Return
 *  SchM_Schedulable_Rte_Rte_ComSendSignalProxyPeriodic_Start
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Return
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Start
 *  SchM_Schedulable_Uart_Uart_MainFunction_Read_Return
 *  SchM_Schedulable_Uart_Uart_MainFunction_Read_Start
 *  SchM_Schedulable_Uart_Uart_MainFunction_Write_Return
 *  SchM_Schedulable_Uart_Uart_MainFunction_Write_Start
 *  SchM_Schedulable_Xcp_CanXcp_MainFunction_Return
 *  SchM_Schedulable_Xcp_CanXcp_MainFunction_Start
 *  SchM_Schedulable_Xcp_Xcp_MainFunction_Return
 *  SchM_Schedulable_Xcp_Xcp_MainFunction_Start
 *
 *********************************************************************************************************************/

/* double include prevention */
#ifndef RTE_HOOK_H
# define RTE_HOOK_H

# include "Os.h" /* PRQA S 0828, 0883 */ /* MD_MSR_Dir1.1, MD_Rte_Os */

# include "Rte_Type.h"
# include "Rte_Cfg.h"

# ifndef RTE_VFB_TRACE
#  define RTE_VFB_TRACE (0)
# endif

#endif /* RTE_HOOK_H */

/**********************************************************************************************************************
 MISRA 2012 violations and justifications
 *********************************************************************************************************************/

/* module specific MISRA deviations:
   MD_Rte_Os:
     Reason:     This justification is used as summary justification for all deviations caused by the MICROSAR OS
                 which is for testing of the RTE. Those deviations are no issues in the RTE code.
     Risk:       No functional risk.
     Prevention: Not required.

*/
